routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/store', 'StoreController', ['as' => 'admin']);
    Route::resource('/agency', 'AgencyController', ['as' => 'admin']);
    Route::resource('/equipment-type', 'EquipmentTypeController', ['as' => 'admin']);
    Route::resource('/task', 'TaskController', ['as' => 'admin']);
    Route::post('/task/go-next/{task}', 'TaskController@goNext')->name('admin.task.go-next');
    Route::post('/task/cancel/{task}', 'TaskController@cancel')->name('admin.task.cancel');
    Route::resource('/task-type', 'TaskTypeController', ['as' => 'admin']);
    Route::resource('/status-type', 'StatusTypeController', ['as' => 'admin']);
    Route::resource('/status-log', 'StatusLogController', ['as' => 'admin']);
});

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/TaskTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\StatusType;
use App\TaskType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class TaskTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.task-types.index',[
           'taskTypes' => TaskType::paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.task-types.create', [
            'taskType' => new TaskType(),
            'statuses' => StatusType::get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        TaskType::create($request->all());

        return redirect()->route('admin.task-type.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\TaskType  $taskType
     * @return \Illuminate\Http\Response
     */
    public function show(TaskType $taskType)
    {
        return view('admin.task-types.show',[
            'taskType' => $taskType,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\TaskType  $taskType
     * @return \Illuminate\Http\Response
     */
    public function edit(TaskType $taskType)
    {
        return view('admin.task-types.edit', [
            'taskType' => $taskType,
            'statuses' => StatusType::get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\TaskType  $taskType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, TaskType $taskType)
    {
        $taskType->update($request->all());

        return redirect()->route('admin.task-type.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\TaskType  $taskType
     * @return \Illuminate\Http\Response
     */
    public function destroy(TaskType $taskType)
    {
        $taskType->delete();

        return redirect()->route('admin.task-type.index');
    }
}

resources/views/admin/task-types/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.task-type.index' => 'Список типов задач'
            ])
            @slot('title') Создание типа задачи @endslot
        @endcomponent

        <form action="{{ route('admin.task-type.store') }}" method="post" class="form-horizontal">
            {{ csrf_field() }}

            @include('admin.task-types.partials.form')

        </form>

    </div>

@endsection

resources/views/admin/task-types/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.task-type.index' => 'Список типов задач'
            ])
            @slot('title') Редактирование типа задачи @endslot
        @endcomponent

        <form action="{{ route('admin.task-type.update', $taskType) }}" method="post" class="form-horizontal">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            @include('admin.task-types.partials.form')

        </form>

    </div>

@endsection

resources/views/admin/task-types/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [])
            @slot('title') Список типов задач @endslot
        @endcomponent

        <a href="{{ route('admin.task-type.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>
            Добавить тип задачи</a>

        <table class="table table-striped table-bordered mt-3">
            <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Начальный статус</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @forelse ($taskTypes as $taskType)
                <tr>
                    <td><a href="{{ route('admin.task-type.show', $taskType) }}">{{ $taskType->title }}</a></td>
                    <td>{{ $taskType->description }}</td>
                    <td>{{ $taskType->startStatus->title }} - <small>{{ $taskType->startStatus->description }}</small></td>
                    <td class="text-right">
                        <form action="{{ route('admin.task-type.destroy', $taskType) }}"
                              onsubmit="return confirm('Удалить?');" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field() }}
                            <a href="{{ route('admin.task-type.edit', $taskType) }}"><i class="fa fa-edit"></i></a>
                            <button type="submit" class="btn btn-link"><i class="fa fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" class="text-center"><h2>Данные отсутствуют</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="4">
                    <ul class="pagination pull-right">
                        {{ $taskTypes->links() }}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection

resources/views/admin/task-types/show.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.task-type.index' => 'Список типов задач'
            ])
            @slot('title') Тип задачи {{ $taskType->title }} @endslot
        @endcomponent

        <p>Заголовок: {{ $taskType->title }}</p>
        <p>Описание: {{ $taskType->description }}</p>
        <p>Начальный статус: {{ $taskType->startStatus->title }} - <small>{{ $taskType->startStatus->description }}</small></p>

    </div>

@endsection