routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/store', 'StoreController', ['as' => 'admin']);
    Route::resource('/agency', 'AgencyController', ['as' => 'admin']);
    Route::resource('/equipment-type', 'EquipmentTypeController', ['as' => 'admin']);
    Route::resource('/task', 'TaskController', ['as' => 'admin']);
    Route::post('/task/go-next/{task}', 'TaskController@goNext')->name('admin.task.go-next');
    Route::post('/task/cancel/{task}', 'TaskController@cancel')->name('admin.task.cancel');
    Route::resource('/task-type', 'TaskTypeController', ['as' => 'admin']);
    Route::resource('/status-type', 'StatusTypeController', ['as' => 'admin']);
    Route::resource('/status-log', 'StatusLogController', ['as' => 'admin']);
});

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/StatusTypeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\StatusType;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class StatusTypeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.status-types.index', [
            'statusTypes' => StatusType::orderBy('id', 'desc')->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.status-types.create', [
            'statusType' => new StatusType(),
            'statuses' => StatusType::get(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        StatusType::create(array_merge($request->except(['required']), ['required' => join(',', $request->get('required',[]))]));

        return redirect()->route('admin.status-type.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\StatusType $statusType
     * @return \Illuminate\Http\Response
     */
    public function show(StatusType $statusType)
    {
        return view('admin.status-types.show', [
            'statusType' => $statusType,
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\StatusType $statusType
     * @return \Illuminate\Http\Response
     */
    public function edit(StatusType $statusType)
    {
        return view('admin.status-types.edit', [
            'statusType' => $statusType,
            'statuses' => StatusType::where('id', '!=', $statusType->id)->get(),
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  \App\StatusType $statusType
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, StatusType $statusType)
    {

        $statusType->update(array_merge($request->except(['required']), ['required' => join(',', $request->get('required',[]))]));

        return redirect()->route('admin.status-type.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\StatusType $statusType
     * @return \Illuminate\Http\Response
     */
    public function destroy(StatusType $statusType)
    {
        $statusType->delete();

        return redirect()->route('admin.status-type.index');
    }
}

resources/views/admin/status-types/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.status-type.index' => 'Список типов стстусов'
            ])
            @slot('title') Создание типа статуса @endslot
        @endcomponent

        <form action="{{ route('admin.status-type.store') }}" method="post" class="form-horizontal">
            {{ csrf_field() }}

            @include('admin.status-types.partials.form')

        </form>

    </div>

@endsection

resources/views/admin/status-types/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.status-type.index' => 'Список типов стстусов'
            ])
            @slot('title') Редактирование типа стстусов @endslot
        @endcomponent

        <form action="{{ route('admin.status-type.update', $statusType) }}" method="post" class="form-horizontal">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            @include('admin.status-types.partials.form')

        </form>

    </div>

@endsection

resources/views/admin/status-types/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [])
            @slot('title') Список типов статусов @endslot
        @endcomponent

        <a href="{{ route('admin.status-type.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i>
            Добавить тип статуса</a>

        <table class="table table-striped table-bordered mt-3">
            <thead>
            <tr>
                <th>Название</th>
                <th>Описание</th>
                <th>Следующий</th>
                <th>Автоматическое переключение</th>
                <th>Требуемые поля</th>
                <th>Отмена</th>
                <th>Вызов функции при смене статуса</th>
                <th>Действие</th>
            </tr>
            </thead>
            <tbody>
            @forelse ($statusTypes as $statusType)
                <tr>
                    <td><a href="{{ route('admin.status-type.show', $statusType) }}">{{ $statusType->title }}</a></td>
                    <td>{{ $statusType->description }}</td>
                    <td>{{ $statusType->nextStatus->title }} - <small>{{ $statusType->nextStatus->description }}</small></td>
                    <td>@if($statusType->autoNext) Да @else Нет @endif</td>
                    <td>{{ $statusType->requiredString() }}</td>
                    <td>{{ $statusType->cancelStatus->title }} - <small>{{ $statusType->cancelStatus->description }}</small></td>
                    <td>{{ $statusType->callback }}</td>
                    <td class="text-right">
                        <form action="{{ route('admin.status-type.destroy', $statusType) }}"
                              onsubmit="return confirm('Удалить?');" method="POST">
                            <input type="hidden" name="_method" value="DELETE">
                            {{ csrf_field() }}
                            <a href="{{ route('admin.status-type.edit', $statusType) }}"><i class="fa fa-edit"></i></a>
                            <button type="submit" class="btn btn-link"><i class="fa fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" class="text-center"><h2>Данные отсутствуют</h2></td>
                </tr>
            @endforelse
            </tbody>
            <tfoot>
            <tr>
                <td colspan="8">
                    <ul class="pagination pull-right">
                        {{ $statusTypes->links() }}
                    </ul>
                </td>
            </tr>
            </tfoot>
        </table>
    </div>

@endsection

resources/views/admin/status-types/show.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.status-type.index' => 'Список типов статусов'
            ])
            @slot('title') Тип статуса {{ $statusType->title }} @endslot
        @endcomponent

        <p>Заголовок: {{ $statusType->title }}</p>
        <p>Следующий: {{ $statusType->nextStatus->title }} - <small>{{ $statusType->nextStatus->description }}</small></p>
        <p>Автоматическое переключение: @if($statusType->autoNext) Да @else Нет @endif</p>
        <p>Требуемые поля: {{ $statusType->requiredString() }}</p>
        <p>Отмена: {{ $statusType->cancelStatus->title }} - <small>{{ $statusType->cancelStatus->description }}</small></p>
        <p>Вызов функции при смене статуса: {{ $statusType->callback }}</p>

    </div>

@endsection