routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix' => 'admin', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {
    Route::get('/', 'DashboardController@dashboard')->name('admin.index');
    Route::resource('/store', 'StoreController', ['as' => 'admin']);
    Route::resource('/agency', 'AgencyController', ['as' => 'admin']);
    Route::resource('/equipment-type', 'EquipmentTypeController', ['as' => 'admin']);
    Route::resource('/task', 'TaskController', ['as' => 'admin']);
    Route::post('/task/go-next/{task}', 'TaskController@goNext')->name('admin.task.go-next');
    Route::post('/task/cancel/{task}', 'TaskController@cancel')->name('admin.task.cancel');
    Route::resource('/task-type', 'TaskTypeController', ['as' => 'admin']);
    Route::resource('/status-type', 'StatusTypeController', ['as' => 'admin']);
    Route::resource('/status-log', 'StatusLogController', ['as' => 'admin']);
});

Route::get('/', function () {
    return redirect()->route('home');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Agency.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Agency
 *
 * @mixin \Eloquent
 */
class Agency extends BaseModel
{
    protected $fillable = ['title'];
}

app/Http/Controllers/Admin/AgencyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Agency;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AgencyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.agencies.index', [
            'agencies' => Agency::orderBy('title')->paginate(10),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.agencies.create', [
            'agency' => new Agency(),
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Agency::create($request->all());

        return redirect()->route('admin.agency.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function show(Agency $agency)
    {
        return view('admin.agencies.show', [
            'agency' => $agency
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function edit(Agency $agency)
    {
        return view('admin.agencies.edit', [
            'agency' => $agency
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Agency $agency)
    {
        $agency->update($request->all());

        return redirect()->route('admin.agency.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Agency  $agency
     * @return \Illuminate\Http\Response
     */
    public function destroy(Agency $agency)
    {
        $agency->delete();

        return redirect()->route('admin.agency.index');
    }
}

resources/views/admin/agencies/create.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.agency.index' => 'Список агентств'
            ])
            @slot('title') Создание агентства @endslot
        @endcomponent

        <form action="{{ route('admin.agency.store') }}" method="post" class="form-horizontal">
            {{ csrf_field() }}

            @include('admin.agencies.partials.form')

        </form>

    </div>

@endsection

resources/views/admin/agencies/edit.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.agency.index' => 'Список агентств'
            ])
            @slot('title') Редактирование агентства @endslot
        @endcomponent

        <form action="{{ route('admin.agency.update', $agency) }}" method="post" class="form-horizontal">
            <input type="hidden" name="_method" value="put">
            {{ csrf_field() }}

            @include('admin.agencies.partials.form')

        </form>

    </div>

@endsection

resources/views/admin/agencies/index.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [])
            @slot('title') Список агентств @endslot
        @endcomponent

        <a href="{{ route('admin.agency.create') }}" class="btn btn-primary pull-right"><i class="fa fa-plus"></i> Добавить агентство</a>

        <table class="table table-striped table-bordered mt-3">
            <thead>
                <tr>
                    <th>Название</th>
                    <th>Действие</th>
                </tr>
            </thead>
            <tbody>
                @forelse ($agencies as $agency)
                    <tr>
                        <td><a href="{{ route('admin.agency.show', $agency) }}">{{ $agency->title }}</a></td>
                        <td class="text-right">
                            <form action="{{ route('admin.agency.destroy', $agency) }}" onsubmit="return confirm('Удалить?');" method="POST">
                                <input type="hidden" name="_method" value="DELETE">
                                {{ csrf_field() }}
                                <a href="{{ route('admin.agency.edit', $agency) }}"><i class="fa fa-edit"></i></a>
                                <button type="submit" class="btn btn-link"><i class="fa fa-trash"></i></button>
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr><td colspan="2" class="text-center"><h2>Данные отсутствуют</h2></td></tr>
                @endforelse
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="3">
                        <ul class="pagination pull-right">
                            {{ $agencies->links() }}
                        </ul>
                    </td>
                </tr>
            </tfoot>
        </table>
    </div>

@endsection

resources/views/admin/agencies/show.blade.php
@extends('admin.layouts.app_admin')

@section('content')

    <div class="container">
        @component('admin.components.breadcrumb')
            @slot('pages', [
                'admin.agency.index' => 'Список агентств'
            ])
            @slot('title') Агентство {{ $agency->title }} @endslot
        @endcomponent

        <p>Заголовок: {{ $agency->title }}</p>

    </div>

@endsection